#!/usr/bin/env bash
export POSIXLY_CORRECT=y

comflg=0

while true ; do
    case "$1" in
	-a )
           case "$2" in
                *) ARG_A="$2" ; shift 2 ;;  
            esac ;;
        -b )
	   case "$2" in
                *) ARG_B="$2" ; shift 2 ;;
            esac ;;
	-ip )
           case "$2" in
                *) ARG_IP="$2" ; shift 2 ;;
            esac ;;
	-uri )
           case "$2" in
                *) ARG_URI="$2" ; shift 2 ;;
            esac ;;

	list-ip ) comflg=1; shift; break ;;
        list-hosts ) comflg=2; shift; break ;;
        list-uri ) comflg=3; shift; break ;;
        hist-ip ) comflg=4; shift; break ;;
        hist-load ) comflg=5; shift; break ;;
	
	*) break ;;
    esac
 
done

if [ "$1" == "list-ip" ] || [ "$1" == "list-hosts" ] || [ "$1" == "list-uri" ] || [ "$1" == "hist-ip" ] || [ "$1" == "hist-load" ]; then
                echo "Chyba, dva prikazy!" ; exit 1
fi
	

if [ ! -z "$ARG_A" ]; then
	A_exist=0
        A_zprac=$(echo "$ARG_A" | tr -d -c 0-9)
else
        A_exist=1
fi

if [ ! -z "$ARG_B" ]; then
	B_exist=0
        B_zprac=$(echo "$ARG_B" | tr -d -c 0-9)
else
        B_exist=1
fi

declare -a pole_radku


a=${#*}
if [ "$a" = 0 ]; then
	a=1
fi

IFS=$'\n'

for i in $(seq "$a")
do	
        param=${!i}
	echo $param
	dzip=$(echo "$param" | grep -o ".*\.gz")
	if [ ! -z "$dzip" ]; then
		soubor=$(gunzip -c "$param") || { echo "gunzip souboru $param se nepodaril!" ; exit 1; }
	elif [ ! -z "$param" ]; then
		soubor=$(cat "$param") || { echo "soubor $param se nepodarilo otevrit!" ; exit 1; }
	elif [ -z "$param" ]; then
		soubor=$(</dev/stdin)
		printf "\n"
	fi	



	for line in $(echo "$soubor"); do
  
	if [ "$A_exist" = 0 ] || [ "$B_exist" = 0 ]; then
		datum_do_cisla=$(echo `echo "$line" | grep -E -o "([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2})"` | tr -d -c 0-9) 
		if [ -n "$datum_do_cisla" ] && [ "$datum_do_cisla"" -eq "$datum_do_cisla"" ] 2>/dev/null; then
			nic=1  			
		else
			
  			echo "Spatny format datumu v souboru! (Spravny format je YYYY-MM-DD HH:MM:SS)"; exit 1
		fi		


		if [ "$A_exist" = 0 ]; then
			if [ "$datum_do_cisla" -le "$A_zprac" ]; then
				continue
			fi

		fi

		if [ "$B_exist" = 0 ]; then
                        if [ "$datum_do_cisla" -ge "$B_zprac" ]; then
                                continue
                        fi

                fi
	fi

	if [ ! -z "$ARG_IP" ]; then		
		radek_s_ARG_IP=$(echo "$line" | grep -o "$ARG_IP")
		#echo "$radek_s_ARG_IP"
		if [ -z "$radek_s_ARG_IP" ]; then
			continue
		fi

	fi
		
	if [ ! -z "$ARG_URI" ]; then
		radek_s_URI=$(echo "$line" | grep -o "$ARG_URI")
		if [ -z "$radek_s_URI" ]; then
                	continue
                fi
	fi


	if [ "$comflg" = 0 ]; then
		echo "$line"

	elif [ "$comflg" = 1 ]; then
		konec=0
		radek_s_list_ip=$(echo "$line" | grep -E -o "(([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})|(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7})))")
			
		for c in "${pole_radku[@]}"; do					
    			if [ "$c" == "$radek_s_list_ip" ] ; then
				konec=1
        			break
    			fi
				
		done

		if [ "$konec" = 0 ]; then
			pole_radku+=("$radek_s_list_ip")
                        echo "$radek_s_list_ip"
		fi	

	elif [ "$comflg" = 2 ]; then
		konec=0

		radek_pro_host=$(echo "$line" | grep -E -o "(([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})|(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7})))")
		if [ -z "$radek_pro_host" ]; then
			continue
		fi
		
		for c in "${pole_radku[@]}"; do
                       if [ "$c" == "$radek_pro_host" ] ; then
                               konec=1
                               break
                       fi

                done

		if [ "$konec" = 0 ]; then
                        pole_radku+=("$radek_pro_host")

			x=$(host "$radek_pro_host" | grep -E ".*NXDOMAIN.*|.*SERVFAIL.*")

			if [ ! -z "$x" ]; then	
				echo "$radek_pro_host"
			else			
				echo `host "$radek_pro_host" | sed 's|.*pointer ||g'`
			fi
		fi

	elif [ "$comflg" = 3 ]; then
		konec=0
		radek_pro_listuri=$(echo "$line" | grep -E -o ".*GET.*|.*POST.*|.*HEAD.*" |  sed -r 's|.*GET \|.*POST \|.*HEAD ||g' | sed -r 's|HTTP.*||g')
		if [ -z "$radek_pro_listuri" ]; then
			continue
		fi

		for c in "${pole_radku[@]}"; do
                      if [ "$c" == "$radek_pro_listuri" ] ; then
                              konec=1
                              break
                      fi

                done

		if [ "$konec" = 0 ]; then
                        pole_radku+=("$radek_pro_listuri")
			echo "$radek_pro_listuri"
		fi
	fi						
	done
done  


exit 0
