# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRemovefromcart():

    @Given('Uživatel je na stránce "Shopping Cart".')
    def setUp(self):
        dp = {'browserName': 'firefox', 'marionette': 'true',
                'javascriptEnabled': 'true'}
        self.driver = webdriver.Remote(
        command_executor='http://mys01.fit.vutbr.cz:4444/wd/hub',
        desired_capabilities=dp)
        #desired_capabilities=DesiredCapabilities.FIREFOX)
        self.driver.implicitly_wait(15)
        self.base_url = "http://mys01.fit.vutbr.cz:8019/"
        self.verificationErrors = []
        self.accept_next_alert = True
    

    def teardown_method(self, method):
        self.driver.quit()
  

    @When('Uživatel klikne u příslušného produktu na červené tlačítko "Remove"')
    def test_removefromcart(self):
        self.driver.get("http://mys01.fit.vutbr.cz:8019/index.php?route=product/product&product_id=30")
        self.driver.find_element(By.ID, "input-option226").click()
        self.driver.find_element(By.XPATH, "//div[@id=\'product\']/div/select").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
        self.driver.find_element(By.ID, "button-cart").click()
        self.driver.execute_script("window.scrollTo(0,94)")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-inverse").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > strong").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger:nth-child(2)").click()

    @Then('Příslušný produkt byl odebrán z košíku.')
    def empty(self):
        assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").text == "Your shopping cart is empty!"
  
