/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "MyVariables.h"
#include <stdio.h> 


static int number = 4;
static int tmp;


#ifdef _WIN32 
    char os[] = "My operating system is Windows!";
#elif __APPLE__ || TARGET_OS_MAC
    char os[] = "My operating system is MAC!";
#elif __linux__ 
    char os[] = "My operating system is Linux!";
#elif __ANDROID__ 
    char os[] = "My operating system is Android!";
#elif __unix__ 
    char os[] = "My operating system is Unix!";
#elif __sun || BSD 
    char os[] = "My operating system is Solaris OS!";
#elif __DragonFly__ 
    char os[] = "My operating system is DragonFly BSD OS!";
#elif __FreeBSD__ 
    char os[] = "My operating system is FreeBSD OS!";
#elif __NetBSD__ 
    char os[] = "My operating system is Net BSD OS!";
#elif __OpenBSD__ 
    char os[] = "My operating system is Open BSD OS!";
#else 
    char os[] = "Sorry, i dont know my operation system!";
#endif

/** Initializes the MyVariables module */
void init_MyVariables(void)
{
    const oid LoginString_oid[] = { 1,3,6,1,3,22,1 };
    const oid TimeString_oid[] = { 1,3,6,1,3,22,2 };
    const oid ReadWriteInteger_oid[] = { 1,3,6,1,3,22,3 };
    const oid OpSysString_oid[] = { 1,3,6,1,3,22,4 };

    DEBUGMSGTL(("MyVariables", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("LoginString", handle_LoginString,
                               LoginString_oid, OID_LENGTH(LoginString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("TimeString", handle_TimeString,
                               TimeString_oid, OID_LENGTH(TimeString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ReadWriteInteger", handle_ReadWriteInteger,
                               ReadWriteInteger_oid, OID_LENGTH(ReadWriteInteger_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("OpSysString", handle_OpSysString,
                               OpSysString_oid, OID_LENGTH(OpSysString_oid),
                               HANDLER_CAN_RONLY
        ));
}

int handle_LoginString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    const char login[] = "xdvora3d";
    

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, login, sizeof(login)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_LoginString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int handle_TimeString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    

    	time_t now;
  	time(&now);
  	struct tm *p = localtime(&now);
  	char buff[21];
	
  	strftime(buff, sizeof buff - 1, "%FT%T", p);
  	
	buff[16] = '.';
	buff[19] = 'Z';
  	


    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, buff, sizeof(char)*20);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_TimeString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int handle_ReadWriteInteger(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &number, sizeof(number));
            break;

        case MODE_SET_RESERVE1:
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) 
		{
                	netsnmp_set_request_error(reqinfo, requests, ret );
            	}
            break;

        case MODE_SET_RESERVE2:
	    tmp = number;
	    break;
	
        case MODE_SET_FREE:
            break;

        case MODE_SET_ACTION:
            number = *(requests->requestvb->val.integer);
            break;

        case MODE_SET_COMMIT:
            break;

        case MODE_SET_UNDO:
            number = tmp;
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ReadWriteInteger\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_OpSysString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, os, sizeof(os)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_OpSysString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

