/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MYVARIABLES_H
#define MYVARIABLES_H

/* function declarations */
void init_MyVariables(void);
Netsnmp_Node_Handler handle_LoginString;
Netsnmp_Node_Handler handle_TimeString;
Netsnmp_Node_Handler handle_ReadWriteInteger;
Netsnmp_Node_Handler handle_OpSysString;

#endif /* MYVARIABLES_H */
